config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :labels
  root to: 'sessions#new'
  resources :sessions, only: %i[new create destroy new_guest] do
    collection do
      post :new_guest, as: 'guest_sign_in'
    end
  end
  resources :users
  resources :tasks
  namespace :admin do
    resources :users
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :tasks
  validates :user_name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: { minimum: 6 }
  before_validation { email.downcase! }
  has_secure_password

  before_destroy :user_should_have_at_least_one

  private

  def user_should_have_at_least_one
    if User.where(admin: true).count == 0
      errors.add :base, '少なくとも1つ、管理用のアカウントが必要です'
      throw :abort
    end
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

class Admin::UsersController < ApplicationController
  before_action :set_user, only: %i[show update edit destroy]
  before_action :admin_user

  def index
    @users = User.all.order(created_at: :desc).page(params[:page]).per(10)

    if params[:sort_updated]
      @users = User.order(updated_at: :desc).page(params[:page]).per(10)
    end

    if params[:sort_created]
      @users = User.order(created_at: :desc).page(params[:page]).per(10)
    end

    if params.dig(:user, :search)
      @users = User.where('user_name LIKE ?', "%#{params[:user][:user_name]}%").where('email LIKE ?', "%#{params[:user][:email]}%").page(params[:page]).per(10)
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        if @user&.authenticate(user_params[:password])
          session[:user_id] = @user.id
          format.html { redirect_to user_path(@user.id), notice: '新しくアカウントを作りました' }
          format.json { render :show, status: :created, location: @user }
        end
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def show
    @tasks = @user.tasks.all
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: '更新しました' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:user_name, :email, :password,
                                 :password_confirmation, :admin)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show update edit destroy]
  before_action :render_page, except: %i[new create]

  def new
    if logged_in?
      redirect_to tasks_path, notice: 'アカウントを新規作成する場合、ログアウトして下さい'
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      if @user&.authenticate(user_params[:password])
        session[:user_id] = @user.id
        redirect_to user_path(@user.id), notice: '新しくアカウントを作りました'
      end
    else
      render :new
    end
  end

  def edit
    if @user.user_name == 'admin'
      redirect_to admin_users_path, notice: 'このユーザは編集できません！'
    end

    if current_user.admin == false
      unless @user.id == current_user.id
        redirect_to new_session_path, notice: 'アカウントが違います。アクセスするには再ログインしてください'
      end
    end
  end

  def show
    if current_user.admin == false
      if @user.id != current_user.id
        redirect_to tasks_path, notice: 'アカウントが違います。アクセスするには再ログインしてください'
      end
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: '更新しました'
    else
      render :edit
    end
  end

  def destroy
    if @user.user_name == 'admin'
      redirect_to admin_users_path, notice: 'このユーザは削除できません'
    else
      @user.destroy
      redirect_to admin_users_path, notice: 'ユーザを削除しました'
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:user_name, :email, :password,
                                 :password_confirmation, :admin)
  end
end

app/helpers/admin/users_helper.rb
# frozen_string_literal: true

module Admin::UsersHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_form.html.erb
<div class="container-fluid text-center">
  <%= form_with(model: user, local: true) do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "件のエラー") %> により、このタスクを保存できませんでした</h2>

        <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <br>
    <div class="row justify-content-center">
      <%= form.label :user_name, class: "sr-only" %>
      <%= form.text_field :user_name, class: "form-control task_new",id: "inputUser",placeholder: "お名前" %>
    </div>
    <br>
    <div class="row justify-content-center">
      <%= form.label :email, class: "sr-only" %>
      <%= form.text_field :email, autofocus: true, autocomplete: "email", autocomplete: "email" ,class: "form-control task_new",id: "inputUser",placeholder: "メールアドレス" %>
    </div>
    <br>
    <div class="row justify-content-center">
      <%= form.label :password, class: "sr-only" %>
      <%= form.password_field :password, autocomplete: "new-password" ,class: "form-control task_new",id: "inputUser",placeholder: "パスワード (６文字以上) " %>
    </div>
    <br>
    <div class="row justify-content-center">
      <%= form.label :password_confirmation, class: "sr-only" %>
      <%= form.password_field :password_confirmation, autocomplete: "new-password" ,class: "form-control task_new",id: "inputUser",placeholder: "確認用パスワード" %>
    </div>
    <br>
    <div class="row justify-content-center col-xs-3">
      <%= form.submit "登録" ,class: "btn btn-lg btn-primary " %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container-fluid text-center">
  <br>
  <h1>プロフィール編集</h1>

  <%= render 'form', user: @user %>
  <br>
  <%= link_to '戻る', :back %>
</div>

app/views/users/new.html.erb
<div class="container-fluid text-center">
  <br>
  <h1>ユーザ登録</h1>

  <%= render 'form', user: @user %>
  <br>
  <%= link_to '戻る', :back if logged_in? %>
  <p><%= link_to 'ゲストログイン（閲覧用）', guest_sign_in_sessions_path, method: :post ,class: "btn btn-outline-success" unless logged_in? %></p>
  <p><%= link_to 'ログイン画面', new_session_path,class: "btn btn-outline-secondary btn-xs" unless logged_in? %></p>
</div>

app/views/users/show.html.erb
<div class="container-fluid text-center">
  <div class="card w-50 task_card">
    <p id="notice"><%= notice %></p>

    <h2>
      <%= @user.user_name %>さんのタスク
    </h2>
    <hr>
    <p>
      <strong>タスク合計：</strong>
      <%= @user.tasks.count%>
    </p>

    <p>
      <strong>未着手:</strong>
      <%= @user.tasks.where(status: "未着手").count %>
    </p>

    <p>
      <strong>着手中:</strong>
      <%= @user.tasks.where(status: "着手中").count %>
    </p>
    <p>
      <strong>完了:</strong>
      <%= @user.tasks.where(status: "完了").count %>
    </p>

    <% if logged_in? && @user.id == current_user.id %>
      <p>
        <%= link_to 'プロフィール編集', edit_user_path(@user), class:"btn btn-primary mb-1"  unless @user.user_name == 'admin'  || @user.user_name == "ゲストユーザー" %>
      </p>
    <% end %>
    <p>
      <%= link_to '戻る', tasks_path %>
    </p>
  </div>
</div>