config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :labels
  root to: 'sessions#new'
  resources :sessions, only: %i[new create destroy new_guest] do
    collection do
      post :new_guest, as: 'guest_sign_in'
    end
  end
  resources :users
  resources :tasks
  namespace :admin do
    resources :users
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManyouTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid" id="wrapper">
      <nav class="navbar navbar-expand-md navbar-dark bg-primary">
        <% if logged_in? && current_user.admin == true %>
          <%= link_to "TASK APP(ADMIN)", tasks_path, class: "navbar-brand" %>
        <% else %>
          <%= link_to "TASK APP", tasks_path, class: "navbar-brand" %>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <% if logged_in? %>
              <li class="nav-item active">
                <%= link_to "タスク一覧", tasks_path,class: "nav-link" %>
              </li>
              <li class="nav-item active">
                <%= link_to "マイページ", user_path(current_user.id),class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'ユーザ管理ページ', admin_users_path ,class: "nav-link" if current_user.admin == true %>
              </li>
              <li class="nav-item">
                <%= link_to 'タスク追加', new_task_path ,class: "nav-link" %>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  並び替える
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <%= link_to "終了期限でソートする", tasks_path(sort_deadline: "true"),class: "dropdown-item" %>
                  <%= link_to "優先順位でソートする", tasks_path(sort_priority: "true"),class: "dropdown-item" %>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  ラベルで検索
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <%= form_with(url: tasks_path, method: :get, local: true, class: 'form-inline my-2 my-lg-0 ml-auto') do |form| %>
                    <%= form.label :name, "ラベルで検索" %>
                    <%= form.select("label_id", Label.pluck(:name, :id), { include_blank: true }) %>
                    <%= form.submit 'Search', name: nil, class: "btn btn-outline-info btn-sm" %>
                  <% end %>
                </div>
              </li>
              <li class="nav-item" >
                <%= link_to "ログアウト", session_path(current_user.id), method: :delete, data: { confirm: 'ログアウトしますか？' },class: "nav-link"  %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "ユーザ登録", new_user_path ,class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン", new_session_path ,class: "nav-link" %>
              </li>
            <% end %>
          </ul>
          <%= render 'tasks/search_form' %>
        </div>
      </nav>
      <%= yield %>
      <footer class="footer">
        <p>運営会社YAMAMOTO株式会社</p>
        <p>Copyright © 2000-2020 YAMAMOTO All Rights Reserved.</p>
      </footer>
    </div>
  </body>
</html>